In [3]:
import pandas as pd
import numpy as np

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model

TensorFlow version: 2.15.0


In [4]:
## we have text document so we need to convert it into vector or integer numeric format .so there are two way that converts documents of words into numeric


In [5]:
##1. Integer Encoding

In [6]:
text=["my name is chetana",
      "i am data scientist","i love to play with data",
      "i have experties in python, machine leraning, MySQL etc","i can make data for to talk"]

In [7]:
from keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(oov_token="chetana")

oov_token="chetana" is setting the out-of-vocabulary (OOV) token to "chetana". This token is used to represent words that are not found in the vocabulary during tokenization. When a word that is not in the vocabulary is encountered, it will be replaced with this OOV token. This is useful for handling unseen words during model training and inference.

In [8]:
tokenizer.fit_on_texts(text) ##it will convert sentenses into token , lower case also it will give indexes of words

In [9]:
tokenizer.word_index  ## It will generate and give index to the each words present into the text documnets

{'chetana': 8,
 'i': 2,
 'data': 3,
 'to': 4,
 'my': 5,
 'name': 6,
 'is': 7,
 'am': 9,
 'scientist': 10,
 'love': 11,
 'play': 12,
 'with': 13,
 'have': 14,
 'experties': 15,
 'in': 16,
 'python': 17,
 'machine': 18,
 'leraning': 19,
 'mysql': 20,
 'etc': 21,
 'can': 22,
 'make': 23,
 'for': 24,
 'talk': 25}

In [10]:
tokenizer.word_counts ## we can count the frequency of each words

OrderedDict([('my', 1),
             ('name', 1),
             ('is', 1),
             ('chetana', 1),
             ('i', 4),
             ('am', 1),
             ('data', 3),
             ('scientist', 1),
             ('love', 1),
             ('to', 2),
             ('play', 1),
             ('with', 1),
             ('have', 1),
             ('experties', 1),
             ('in', 1),
             ('python', 1),
             ('machine', 1),
             ('leraning', 1),
             ('mysql', 1),
             ('etc', 1),
             ('can', 1),
             ('make', 1),
             ('for', 1),
             ('talk', 1)])

In [11]:
sequnces=tokenizer.texts_to_sequences(text)

In [12]:
sequnces #3 it will genearte sequnces for each word in text


[[5, 6, 7, 8],
 [2, 9, 3, 10],
 [2, 11, 4, 12, 13, 3],
 [2, 14, 15, 16, 17, 18, 19, 20, 21],
 [2, 22, 23, 3, 24, 4, 25]]

In [13]:
##Here we can see in our text 1st senetense is "my name is chetana"
##so texts_to_sequences search the indexes for each word from generated index and will convert the sententecs into numeric form

In [14]:
##In next step we will apply padding to make it same size

In [15]:
from keras.utils import pad_sequences

In [16]:
sequences=pad_sequences(sequnces,padding="post") ##post means it will add zeros after

In [17]:
sequences

array([[ 5,  6,  7,  8,  0,  0,  0,  0,  0],
       [ 2,  9,  3, 10,  0,  0,  0,  0,  0],
       [ 2, 11,  4, 12, 13,  3,  0,  0,  0],
       [ 2, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 2, 22, 23,  3, 24,  4, 25,  0,  0]])

In [18]:
##in this way we created input data

# IMDB data

In [19]:
from keras.datasets import imdb

In [20]:
data=pd.read_csv(r"IMDB Dataset.csv")
data

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [21]:
from sklearn.model_selection import train_test_split
##now we will load imdb data which is already preprocessed
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

# Perform train-test split
X_train, X_test, y_train, y_test = train_test_split(train_data, train_labels, test_size=0.2, random_state=42)

In [22]:
train_data.shape

(25000,)

In [23]:
train_labels

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [24]:
X_train.shape

(20000,)

In [25]:
X_test.shape

(5000,)

In [26]:

# Print the first review from the training set
print("First review from the training set:")
print(X_train[19999])

# Print the corresponding sentiment label (0 for negative, 1 for positive)
print("Sentiment label:")
print(y_train[19999])


First review from the training set:
[1, 480, 20, 13, 219, 14, 20, 18, 4, 86, 58, 23, 6, 2817, 5, 100, 24, 264, 15, 13, 69, 24, 60, 557, 7, 12, 159, 397, 23, 15, 1707, 137, 12, 203, 306, 33, 86, 8, 30, 6, 2284, 509, 12, 9, 6, 22, 15, 316, 144, 67, 5, 80, 358, 349, 106, 14, 20, 19, 294, 25, 119, 25, 80, 358, 12, 17, 76, 17, 59, 127, 5, 12, 80, 603, 25, 194, 757]
Sentiment label:
1


In [27]:
print(X_train[0])

[1, 73, 89, 81, 25, 60, 967, 6, 20, 141, 17, 14, 31, 127, 12, 60, 28, 1360, 1107, 66, 45, 6, 20, 15, 497, 8, 79, 17, 491, 8, 112, 6, 6683, 20, 17, 614, 691, 4, 436, 20, 9, 2855, 6, 762, 7, 493, 8621, 6, 185, 250, 24, 55, 2276, 5, 23, 350, 7, 15, 82, 24, 15, 821, 66, 10, 10, 45, 578, 15, 4, 20, 805, 8, 30, 17, 821, 5, 1621, 17, 614, 190, 4, 20, 9, 43, 32, 99, 1214, 18, 15, 8, 157, 46, 17, 1436, 4, 2, 5, 2, 9, 32, 1796, 5, 1214, 267, 17, 73, 17, 4413, 36, 26, 400, 43, 4562, 83, 4, 1873, 247, 74, 83, 4, 250, 540, 82, 4, 96, 4, 250, 8306, 8, 32, 4, 2, 9, 184, 3966, 13, 384, 48, 14, 16, 147, 1348, 59, 62, 69, 9420, 12, 46, 50, 9, 53, 2, 74, 1930, 11, 14, 31, 151, 10, 10, 4, 20, 9, 540, 364, 352, 5, 45, 6, 2, 589, 33, 269, 8, 2715, 142, 1621, 5, 821, 17, 73, 17, 204, 5, 2908, 19, 55, 1763, 4697, 92, 66, 104, 14, 20, 93, 76, 1488, 151, 33, 4, 58, 12, 188, 626, 151, 12, 215, 69, 224, 142, 73, 237, 6, 964, 7, 1446, 2289, 188, 626, 103, 14, 31, 10, 10, 451, 7, 1465, 5, 599, 80, 91, 1329, 30, 685

In [28]:
len(X_train[0])

259

In [29]:
##This review are already converted into numerical format

In [30]:
len(X_train[1])

520

In [31]:
len(X_train[2])

290

In [32]:
##Here we need to do padding to make it on same size arrays

##Now we will get only sample of data to further model creation and eveluation as the dataset is big in size it will take time

In [33]:
X_train=pad_sequences(X_train,padding="post",maxlen=100)
X_test=pad_sequences(X_test,padding="post",maxlen=100)


In [34]:
len(X_train[0])

100

In [35]:
len(X_train[1])

100

In [36]:
X_train.shape

(20000, 100)

In [37]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense
model=Sequential()

model.add(SimpleRNN(32,input_shape=(100,1),return_sequences=False))  ##Here we are giving 32 nodes and shape is (50,1)
model.add(Dense(1,activation="sigmoid"))

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 32)                1088      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [38]:
## Why shape is (100,1) 100 is timestamps and 1 is input feature
# e.g. There are 100 numbers[11,2,3,23,21,12.....] here when we give this input to the Nueral Nw .
# first 11 will be given to the node  after 2 and after 3 this sequces will be run till last number in the input this inputs will given after particular timestamp



In [ ]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

model.fit(X_train,y_train,epochs=20, validation_data=(X_test,y_test))


Epoch 1/20


625/625 [==============================] - 8s 12ms/step - loss: 0.7047 - accuracy: 0.5063 - val_loss: 0.6919 - val_accuracy: 0.5240
Epoch 2/20
625/625 [==============================] - 7s 11ms/step - loss: 0.6933 - accuracy: 0.5050 - val_loss: 0.6912 - val_accuracy: 0.5266
Epoch 3/20
625/625 [==============================] - 7s 11ms/step - loss: 0.6926 - accuracy: 0.5132 - val_loss: 0.6929 - val_accuracy: 0.5022
Epoch 4/20
625/625 [==============================] - 7s 11ms/step - loss: 0.6930 - accuracy: 0.5055 - val_loss: 0.6922 - val_accuracy: 0.4976
Epoch 5/20
625/625 [==============================] - 7s 12ms/step - loss: 0.6930 - accuracy: 0.5081 - val_loss: 0.6922 - val_accuracy: 0.5246
Epoch 6/20
625/625 [==============================] - 7s 11ms/step - loss: 0.6930 - accuracy: 0.5100 - val_loss: 0.6929 - val_accuracy: 0.5008
Epoch 7/20
625/625 [==============================] - 7s 11ms/step - loss: 0.6931 - accuracy: 0.5074 - val_loss: 0.6938 - val_accuracy: 0.4

In [ ]:
predictions = model.predict(X_test)

In [ ]:
predictions

In [ ]:
# Convert predictions to labels (0 or 1)
predicted_labels = [1 if pred > 0.5 else 0 for pred in predictions]

In [ ]:
X_test[1]

In [ ]:
y_test[1]

In [ ]:
print(predicted_labels)

# Testing on new data

In [ ]:
from keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(oov_token="chetana")

In [ ]:
test_data=["movies was bad","movie was not good"]

In [ ]:
tokenizer.fit_on_texts(test_data)

In [ ]:
tokenizer.word_index

In [ ]:
sequnces=tokenizer.texts_to_sequences(test_data)

In [ ]:
sequnces

In [20]:
train=pad_sequences(sequnces,padding="post",maxlen=100)

In [25]:
train

array([[ 5,  6,  7,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 2,  9,  3, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 2, 11,  4, 12, 13,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0

In [27]:
predictions = model.predict(train)

NameError: name 'model' is not defined

In [23]:
predicted_labels = [1 if pred > 0.5 else 0 for pred in predictions]

NameError: name 'predictions' is not defined

In [24]:
predicted_labels

NameError: name 'predicted_labels' is not defined

# Chat GPT code

In [162]:
import numpy as np
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten
from keras.preprocessing.sequence import pad_sequences

# Load the IMDb dataset
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

# Preprocess the data
max_len = 100  # Max length of sequences
train_data = pad_sequences(train_data, maxlen=max_len)
test_data = pad_sequences(test_data, maxlen=max_len)

# Build the model
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=32, input_length=max_len))
model.add(Flatten())
model.add(Dense(units=1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(train_data, train_labels, epochs=10, batch_size=32, validation_split=0.2)

# Evaluate the model
loss, accuracy = model.evaluate(test_data, test_labels)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

# Make predictions
predictions = model.predict(test_data)


Epoch 1/10
625/625 [==============================] - 4s 5ms/step - loss: 0.5182 - accuracy: 0.7456 - val_loss: 0.3539 - val_accuracy: 0.8438
Epoch 2/10
625/625 [==============================] - 3s 5ms/step - loss: 0.2581 - accuracy: 0.8993 - val_loss: 0.3275 - val_accuracy: 0.8522
Epoch 3/10
625/625 [==============================] - 3s 5ms/step - loss: 0.1466 - accuracy: 0.9574 - val_loss: 0.3392 - val_accuracy: 0.8474
Epoch 4/10
625/625 [==============================] - 4s 6ms/step - loss: 0.0688 - accuracy: 0.9895 - val_loss: 0.3629 - val_accuracy: 0.8478
Epoch 5/10
625/625 [==============================] - 3s 5ms/step - loss: 0.0296 - accuracy: 0.9986 - val_loss: 0.3932 - val_accuracy: 0.8448
Epoch 6/10
625/625 [==============================] - 3s 5ms/step - loss: 0.0144 - accuracy: 0.9996 - val_loss: 0.4189 - val_accuracy: 0.8452
Epoch 7/10
625/625 [==============================] - 3s 5ms/step - loss: 0.0077 - accuracy: 0.9999 - val_loss: 0.4432 - val_accuracy: 0.8458
Epoch 

In [163]:
predictions

array([[0.078906  ],
       [0.99845403],
       [0.98579854],
       ...,
       [0.00142865],
       [0.01426399],
       [0.9255114 ]], dtype=float32)

In [164]:
# Convert prediction to a label (0 or 1)
predicted_labels = [1 if pred > 0.5 else 0 for pred in predictions]

In [165]:
predicted_labels

[0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,


In [174]:
predictions = model.predict(train)

1/1 [==============================] - 0s 28ms/step


In [175]:
predictions

array([[0.00551323],
       [0.00625992]], dtype=float32)